#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/sm8650-common

PRODUCT_COPY_FILES += \
    vendor/samsung/sm8650-common/proprietary/product/etc/permissions/UimService.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/UimService.xml \
    vendor/samsung/sm8650-common/proprietary/system_ext/etc/init/tcmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/tcmd.rc \
    vendor/samsung/sm8650-common/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/samsung/sm8650-common/proprietary/system_ext/etc/seccomp_policy/tcmd.policy:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/seccomp_policy/tcmd.policy \
    vendor/samsung/sm8650-common/proprietary/system_ext/etc/sysconfig/qti_whitelist_system_ext.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/sysconfig/qti_whitelist_system_ext.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio/sku_pineapple/mixer_paths_pineapple_cdp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_pineapple/mixer_paths_pineapple_cdp.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio/sku_pineapple/mixer_paths_pineapple_cdp_wsa883x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_pineapple/mixer_paths_pineapple_cdp_wsa883x.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio/sku_pineapple/mixer_paths_pineapple_mtp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_pineapple/mixer_paths_pineapple_mtp.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio/sku_pineapple/mixer_paths_pineapple_qrd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_pineapple/mixer_paths_pineapple_qrd.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio/sku_pineapple/resourcemanager.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_pineapple/resourcemanager.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio/sku_pineapple/resourcemanager_pineapple_cdp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_pineapple/resourcemanager_pineapple_cdp.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio/sku_pineapple/resourcemanager_pineapple_mtp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_pineapple/resourcemanager_pineapple_mtp.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio/sku_pineapple/resourcemanager_pineapple_qrd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_pineapple/resourcemanager_pineapple_qrd.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio_effects_haptic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects_haptic.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio_effects_sec.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects_sec.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio_effects_spatializer.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects_spatializer.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/audio_policy_configuration_base.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration_base.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/batching.conf:$(TARGET_COPY_OUT_VENDOR)/etc/batching.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/card-defs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/card-defs.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/charger_fw_fstab.qti:$(TARGET_COPY_OUT_VENDOR)/etc/charger_fw_fstab.qti \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/clstc_config_library.xml:$(TARGET_COPY_OUT_VENDOR)/etc/clstc_config_library.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/cne/mwqem.conf:$(TARGET_COPY_OUT_VENDOR)/etc/cne/mwqem.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/cne/profileMwqem.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/profileMwqem.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/dax3_media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dax3_media_codecs_dolby_audio.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/default-permissions/com.qualcomm.qti.cne.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default-permissions/com.qualcomm.qti.cne.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/display/DPU10__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU10__.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/display/advanced_sf_offsets.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/advanced_sf_offsets.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/display/thermallevel_to_fps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/thermallevel_to_fps.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/displayconfig/display_id_4630947039571902851.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4630947039571902851.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/eva/facedetection/bias.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facedetection/bias.dat \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/eva/facedetection/weight.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facedetection/weight.dat \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/eva/facelandmark/bias_1_1.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/bias_1_1.dat \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/eva/facelandmark/bias_1_2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/bias_1_2.dat \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/eva/facelandmark/bias_2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/bias_2.dat \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/eva/facelandmark/bias_3_1.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/bias_3_1.dat \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/eva/facelandmark/bias_3_2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/bias_3_2.dat \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/eva/facelandmark/weight_1_1.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/weight_1_1.dat \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/eva/facelandmark/weight_1_2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/weight_1_2.dat \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/eva/facelandmark/weight_2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/weight_2.dat \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/eva/facelandmark/weight_3_1.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/weight_3_1.dat \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/eva/facelandmark/weight_3_2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/eva/facelandmark/weight_3_2.dat \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/eva/itof/tuning_params_sensor_type_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/eva/itof/tuning_params_sensor_type_1.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/excluded-input-devices.xml:$(TARGET_COPY_OUT_VENDOR)/etc/excluded-input-devices.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/external_camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/external_camera_config.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/gnss_antenna_info.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gnss_antenna_info.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/gpfspath_oem_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gpfspath_oem_config.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/gps.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gps.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service-qti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/android.hardware.drm-service.clearkey.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.clearkey.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/android.hardware.gatekeeper-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/android.hardware.gnss-aidl-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-aidl-service-qti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/camera.unihal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camera.unihal.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/cas-default-lazy.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cas-default-lazy.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/hermesd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hermesd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/hw/init.qti.kernel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.qti.kernel.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/ims_rtp_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/imsdaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdaemon.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.audio.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.audio.samsung.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.qccvendor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qccvendor.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.qti.media.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.media.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.qti.qcv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.qcv.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.spdaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.spdaemon.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init.vendor.sensors.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.sensors.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/init_thermal-engine-v2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_thermal-engine-v2.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/ipacm-diag.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipacm-diag.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/khdm-default-sec.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/khdm-default-sec.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/loc-launcher.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/loc-launcher.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/nfc-service-nxp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nfc-service-nxp.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/nicmd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nicmd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/qdcmss.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qdcmss.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/qesdk-manager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qesdk-manager.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/qesdk-secmanager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qesdk-secmanager.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/qmipriod.debug.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qmipriod.debug.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/qmipriod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qmipriod.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/qms.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qms.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/qseecomd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qseecomd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/qwesd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qwesd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/secure_element-service-nxp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/secure_element-service-nxp.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/shsusrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/shsusrd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/ssgtzd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ssgtzd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/trusteduilistener.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trusteduilistener.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.adsprpc-guestos-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-guestos-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.audio-adsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.audio-adsprpc-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.cdsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.cdsprpc-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.diag.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.diag.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.dsp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.dsp@1.0-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.hardware.trustedui@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.trustedui@1.0-service-qti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.media.c2@1.0-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.memory.pasrmanager-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.memory.pasrmanager-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.pasrknob@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.pasrknob@1.0-service.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.samsung.hardware.camera.provider-service_64.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.camera.provider-service_64.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.samsung.hardware.thermal-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.thermal-default.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.samsung.hardware.vibrator-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.vibrator-default.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.sensors.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.qti.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/init/vendor.sensors.sscrpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.sscrpcd.rc \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/izat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/libese-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libese-nxp.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/libuwb-countrycode.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libuwb-countrycode.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/libuwb-feature.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libuwb-feature.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/libuwb-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libuwb-nxp.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/libuwb-uci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libuwb-uci.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/locale/plmn_delta_eng.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_eng.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/locale/plmn_delta_zh-rCN.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rCN.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/locale/plmn_delta_zh-rHK.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rHK.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/locale/plmn_delta_zh-rTW.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rTW.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/lowi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lowi.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_cliffs_v0/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/media_cliffs_v0/video_system_specs.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_cliffs_v1/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/media_cliffs_v1/video_system_specs.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_codecs_cliffs_v0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_cliffs_v0.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_codecs_cliffs_v1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_cliffs_v1.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_codecs_performance_pineapple.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_pineapple.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_codecs_performance_pineapple_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_pineapple_vendor.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_codecs_pineapple.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_pineapple.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_codecs_pineapple_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_pineapple_vendor.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_pineapple/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/media_pineapple/video_system_specs.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_profiles.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/media_profiles_pineapple.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_pineapple.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/models/acd/event.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/event.eai \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/models/acd/music.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/music.eai \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/models/acd/speech.eai:$(TARGET_COPY_OUT_VENDOR)/etc/models/acd/speech.eai \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/mtu-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtu-conf.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/pdpcnt-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pdpcnt-conf.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/permissions/android.hardware.fingerprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.fingerprint.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_delta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_delta_attaio.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_attaio.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_delta_hktw.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_hktw.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_delta_usagsm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_usagsm.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/plmn_se13.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_se13.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/portrait_data/single_bokeh_feature_vendor.json:$(TARGET_COPY_OUT_VENDOR)/etc/portrait_data/single_bokeh_feature_vendor.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/qms_log_config:$(TARGET_COPY_OUT_VENDOR)/etc/qms_log_config \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sec_audio_volume_curve.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sec_audio_volume_curve.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sec_config_oem:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config_oem \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/atfwd@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/atfwd@2.0.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.base-arm64.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.base-arm64.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.ext-arm64.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.ext-arm64.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-base.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-base.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-xtra-daemon.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-xtra-daemon.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-xtwifi-client.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-xtwifi-client.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/imsrtp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/imsrtp.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/qms.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qms.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/qti-systemd.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qti-systemd.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/qwesd@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qwesd@2.0.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/seccomp_policy/vendor.qti.hardware.dsp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/vendor.qti.hardware.dsp.policy \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/secnvm/k250a_47000400_0.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_47000400_0.img \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/secnvm/k250a_47000403_1.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_47000403_1.img \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/secnvm/k250a_47000406_f.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_47000406_f.img \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/akmlib.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/akmlib.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/json.lst:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/json.lst \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_ak991x_0.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_ak991x_4.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_ak991x_4.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_ak991x_5.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_ak991x_5.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_default_sensors.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_dynamic_sensors.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_dynamic_sensors_template.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_dynamic_sensors_template.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_irq.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_lps22df_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_lps22df_0.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_lps22hh_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_lps22hh_0.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_lsm6dso_0_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_lsm6dso_0_0.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_lsm6dsv_0_2.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_lsm6dsv_0_2.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_power_0.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_qrd_tmd2755_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_qrd_tmd2755_0.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_qsh_ble_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_qsh_ble_0.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_stk3af00_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_stk3af00_0.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lanai_stk3afx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lanai_stk3afx_0.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dso_0.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/lsm6dsv_2.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dsv_2.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/qsh_ble.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_ble.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/qsh_camera_common.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_common.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/qsh_camera_imx688_4.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_imx688_4.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/qsh_camera_imx688_6.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_imx688_6.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/qsh_camera_imx688_6_actuator.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_imx688_6_actuator.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_fmv_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv_legacy.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/situation_audio_policy_volumes_sec.xml:$(TARGET_COPY_OUT_VENDOR)/etc/situation_audio_policy_volumes_sec.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/snapdragon_color_libs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/snapdragon_color_libs_config.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/ssg/ta_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/ta_config.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/ssg/tz_whitelist.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/tz_whitelist.json \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/str/str_preference_data.dat:$(TARGET_COPY_OUT_VENDOR)/etc/str/str_preference_data.dat \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/usecaseKvManager.xml:$(TARGET_COPY_OUT_VENDOR)/etc/usecaseKvManager.xml \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/wifi/indoorchannel.info:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/indoorchannel.info \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/etc/xtwifi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/xtwifi.conf \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/00_generic_xtalk_shape.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/00_generic_xtalk_shape.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b00 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b01 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b02 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b03 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b04 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b05 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b06 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b07 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b08 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b09 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b10 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b11 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b12 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b13 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b14 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b15 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b16 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b17 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b18 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b19 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/CAMERA_ICP_170.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP_170.elf \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/SoundBoosterParam.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SoundBoosterParam.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs35l43-bot-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l43-bot-dsp1-spk-prot.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs35l43-bot-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l43-bot-dsp1-spk-prot.wmfw \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs35l43-rcv-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l43-rcv-dsp1-spk-prot.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs35l43-rcv-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l43-rcv-dsp1-spk-prot.wmfw \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs40l26-a2h.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-a2h.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs40l26-calib.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-calib.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs40l26-calib.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-calib.wmfw \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs40l26-dvl.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-dvl.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs40l26-svc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs40l26-svc1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc1.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs40l26-svc2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc2.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs40l26-svc3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc3.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs40l26-wt1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-wt1.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs40l26-wt2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-wt2.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs40l26-wt3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-wt3.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs40l26.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/cs40l26.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26.wmfw \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/dax_param.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dax_param.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b00 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b01 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b02 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b03 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b04 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b05 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b06 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b07 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b08 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b09 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b10 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b11 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b12 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b13 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b14 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b15 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b16 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b17 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/evass.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b18 \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/mfc/mfc_fw_flash_nu1668.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc/mfc_fw_flash_nu1668.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/nfc/libsn300u_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/nfc/libsn300u_fw.so \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/ss_dsi_panel_PBA_BOOTING_FHD.dat:$(TARGET_COPY_OUT_VENDOR)/firmware/ss_dsi_panel_PBA_BOOTING_FHD.dat \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/vpu30_2v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu30_2v.mbn \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/vpu30_2v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu30_2v_unsigned.mbn \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/vpu33_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu33_4v.mbn \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/vpu33_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu33_4v_unsigned.mbn \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/wlan-connection-roaming-backup.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan-connection-roaming-backup.ini \
    vendor/samsung/sm8650-common/proprietary/vendor/firmware/wlan-connection-roaming.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan-connection-roaming.ini \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/AIAwbModelFront_v1.0.tflite:$(TARGET_COPY_OUT_VENDOR)/lib64/AIAwbModelFront_v1.0.tflite \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/AIAwbModel_v2.3.tflite:$(TARGET_COPY_OUT_VENDOR)/lib64/AIAwbModel_v2.3.tflite \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_s5k3lu.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_s5k3lu.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/com.samsung.tuned.sony_imx564.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.sony_imx564.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/f_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/f_dual_calibration.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/fdconfigsecure.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigsecure.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/samsung/sm8650-common/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin

PRODUCT_PACKAGES += \
    libHpr_RecFace_dl_v1.0.camera.samsung \
    libOpenCv.camera.samsung \
    libmpbase \
    libphotohdr \
    libsec_semRil \
    libsecril-client \
    service-listener-ext-aidl-V1-ndk \
    vendor.samsung.hardware.bluetooth.audio-V2-ndk \
    btaudio_offload_if \
    com.samsung.sensor.hi1337 \
    com.samsung.sensor.hi847 \
    com.samsung.sensor.imx258 \
    com.samsung.sensor.imx374 \
    com.samsung.sensor.imx471 \
    com.samsung.sensor.imx564 \
    com.samsung.sensor.imx754 \
    com.samsung.sensor.s5k3j1 \
    com.samsung.sensor.s5k3k1 \
    com.samsung.sensor.s5k3lu \
    com.samsung.sensor.s5kgn3 \
    com.samsung.sensor.s5khp2 \
    libTsAe_e3 \
    camx.device-impl \
    cdsp_face \
    com.qti.camx.chiiqutils \
    com.qti.feature2.metadataserializer \
    com.qti.qseeaon \
    com.qti.qseeutils \
    com.qti.settings.sm8650 \
    com.qti.stats.common \
    com.qualcomm.qti.dpm.api@1.0 \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libVkLayer_ADRENO_qprofiler \
    libq3dtools_adreno \
    libq3dtools_esx \
    android.hardware.bluetooth.audio-impl-qti \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.bluetooth@1.1-impl-qti \
    android.hardware.gnss-aidl-impl-qti \
    audio.primary.pineapple \
    camera.qcom.sm8650 \
    camera.qcom \
    camera.unihal.default \
    com.qti.chi.override \
    gatekeeper.mdfpp \
    sensors.dynamic_sensor_hal \
    vendor.qti.hardware.bluetooth_audio@2.0-impl \
    vendor.qti.hardware.bluetooth_audio@2.1-impl \
    vendor.qti.hardware.bluetooth_sar@1.1-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.btconfigstore@2.0-impl \
    vendor.qti.hardware.bttpi-impl \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.samsung.hardware.gnss-aidl-impl-sec \
    vulkan.adreno \
    libAIHighRes_interface \
    libAIMFISP.camera.samsung \
    libAIMFISP_core.camera.samsung \
    libAISegmenter_v2.camera.samsung \
    libAImode_wrapper.camera.samsung \
    libAIphoto_core.camera.samsung \
    libAlacSwDec \
    libApeSwDec \
    libBarcodeReader.vendor.quram \
    libBeauty_v4.camera.samsung \
    libBlurDetectionDeepLearning.camera.samsung \
    libCB \
    libDLInterface.camera.samsung \
    libDeviceInfoProvider \
    libDocumentDetector.uniplugin@1.0 \
    libEventFinder.camera.samsung \
    libEvrcSwCodec \
    libFaceService \
    libFace_Landmark_API.camera.samsung \
    libFace_Landmark_Engine.camera.samsung \
    libFastUWDistortionCorrection.camera.samsung \
    libFlacSwDec \
    libGPMTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libHDRVerifier_v1.camera.samsung \
    libHandGesture.camera.samsung \
    libHprFace_GAE_api.camera.samsung \
    libHprVisualEffect \
    libHpr_RecFace_dl_v1.0.camera.samsung_vendor \
    libHpr_RecGAE_cvFeature_v1.0.camera.samsung \
    libHumanSegVideoModel_Vendor \
    libIDDQD_core \
    libLightObjectDetector_v1.camera.samsung \
    libLocalTM_capture_core.camera.samsung \
    libLocalTM_preview_core \
    libLocalTM_wrapper.camera.samsung \
    libMoireDetection.camera.samsung \
    libMoireDetectionWrapper.camera.samsung \
    libMoireDetector.uniplugin@1.0 \
    libMoonVerifier_v1.camera.samsung \
    libMotionEstimator.camera.samsung \
    libMotionEstimator.uniplugin@1.0 \
    libMotionEstimatorWrapper.camera.samsung \
    libOpenCL \
    libOpenCv.camera.samsung_vendor \
    libPanDetector \
    libPeripheralStateUtils \
    libPersonal_capture.camera.samsung \
    libPersonal_core.camera.samsung \
    libPetDetector_interface \
    libPetDetector_v1.camera.samsung \
    libPortraitSolution.camera.samsung_preview \
    libQRInterface.camera.samsung \
    libQSEEComAPI \
    libQcelp13SwCodec \
    libQrDetector.uniplugin@1.0 \
    libRelighting_API.camera.samsung \
    libSNPE \
    libSRIB_ARVL_HAP.camera.samsung \
    libSWNDFilterPreview.camera.samsung \
    libSceneDetector_v1.camera.samsung \
    libSecJpegEncoder.uniplugin@1.0 \
    libSemDataProps \
    libSemTelephonyProps \
    libSingleTakeBlurDetection.uniplugin@1.0 \
    libSnpeCpu \
    libSnpeGpu \
    libTetraMFP10.camera.samsung \
    libTetraMFP10Tuning.camera.samsung \
    libTouchInputVM \
    libTrustedInput \
    libTrustedInputTZ \
    libTrustedInputUtils \
    libTrustedUI \
    libTrustedUITZ \
    libTrustedUIVM \
    libTsAwbFront_E123 \
    libUniPluginUtils \
    libUniScaler.uniplugin@1.0 \
    libVoiceSdk \
    lib_SamsungRec_08020 \
    lib_SoundAlive_3DPosition_ver202 \
    lib_SoundAlive_AlbumArt_ver105 \
    lib_SoundAlive_play_plus_ver800 \
    lib_SoundBooster_ver2000 \
    lib_bt_aptx \
    lib_bt_ble \
    lib_bt_bundle \
    lib_lvacfs \
    lib_profiler \
    libadm \
    libadreno_app_profiles \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libagm \
    libai_denoiser_interface \
    libaidenoiser \
    libaidenoiserv2 \
    libaivideocentral.arcsoft \
    libar-acdb \
    libar-gpr \
    libar-gsl \
    libar-pal \
    libarcsoft_deflicker_native \
    libarcsoft_dualcam_portraitlighting_preview \
    libarcsoft_object_tracking \
    libarmemlog \
    libatccore \
    libats \
    libaudio_log_utils \
    libauto_framing_arcsoft.uniplugin@1.0 \
    libauto_framing_lite.uniplugin@1.0 \
    libautoframing_object_tracker.camera.samsung \
    libautotracking_interface \
    libbacklight-calib \
    libbatching \
    libbeauty_preview.uniplugin@1.0 \
    libbeautyshot.arcsoft \
    libbitmlengine \
    libbitmlenginev2 \
    libbluetooth_audio_session_aidl_qti \
    libbluetooth_audio_session_qti \
    libbluetooth_audio_session_qti_2_1 \
    libbodyid.arcsoft \
    libbt-hidlclient \
    libbtnv \
    libc++_shared \
    libc2filterplugin \
    libcamxcommonutils \
    libcamxfdengine \
    libcamxhwnodecontext \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxqsatalgo \
    libcamxsettingsmanager \
    libcamxstatscore \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libcapiv2svacnnvendor \
    libcapiv2svarnnvendor \
    libcapiv2udk7vendor \
    libcapiv2uvvendor \
    libcdfw \
    libcdfw_remote_api \
    libcdsp_default_listener \
    libcdsprpc \
    libchilog \
    libclstc_algorithm_adapter \
    libclstc_gcp_adapter \
    libclstc_tm \
    libcommonchiutils \
    libconfigdb \
    libcpion \
    libcv_common \
    libdataitems \
    libdiag \
    libdiagjni \
    libdigital-dimming \
    libdisp-aba \
    libdisplayqos \
    libdisplayskuutils \
    libdpps \
    libdrmfs \
    libdrmtime \
    libdsd2pcm \
    libdsi_netctrl \
    libdsmanager \
    libdsphist_qc \
    libdsutils \
    libdualcam_refocus_video \
    libegis_fp_normal_sensor_test \
    libengine_did \
    libengmode_client \
    libese-grdg \
    libeva \
    libeva_util \
    libevent_finder.uniplugin@1.0 \
    libexifa.camera.samsung \
    libface_landmark.arcsoft \
    libfast_uwdc.uniplugin@1.0 \
    libfastcvdsp_stub \
    libfastcvopt \
    libfeutils \
    libfloatingfeature \
    libfloatingfeature_hal \
    libfocuspeaking \
    libfocuspeaking.uniplugin@1.0 \
    libformatConverter.unifunc \
    libgame_enhance \
    libgaya \
    libgeofencing \
    libgf_in_system_lib \
    libgnss \
    libgnsspps \
    libgps.utils \
    libgpt \
    libgpudataproducer \
    libgralloc_helper.unifunc \
    libgsl \
    libhand_interaction.uniplugin@1.0 \
    libhandgesture.arcsoft \
    libhdr10plus \
    libhdr_backlight_adapter \
    libhdr_stub \
    libhdr_tm \
    libhdradaptivecustom \
    libhdraid.gpu.arcsoft \
    libhdraid.npu.arcsoft \
    libhdrdynamic \
    libhdrdynamicootf \
    libheifcapture \
    libhermes \
    libhermes_bdbridge \
    libhermes_cred \
    libhme \
    libhwvault \
    libhypermotion_core \
    libhypermotion_interface \
    libiddqd.uniplugin@1.0 \
    libidl \
    libimage_enhancement.arcsoft \
    libimage_io \
    libimagecodec_native.quram \
    libimgproc_sw.unifunc@common \
    libintervmipc \
    libipebpsstriping \
    libipebpsstriping170 \
    libipebpsstriping480 \
    libisphwsetting \
    libizat_client_api \
    libizat_core \
    libjpegQtable_interface \
    libjpege \
    libjpegencoder_sw.unifunc \
    libjpegsq.media.samsung \
    libjump_shot.uniplugin@1.0 \
    libkcl \
    libkernelmanager \
    liblbs_core \
    liblistensoundmodel2vendor \
    liblivefocus_preview_engine \
    liblivefocus_preview_interface \
    libllvm-glnext \
    libllvm-qcom \
    libllvm-qgl \
    libloadalgo_stub \
    libloc_api_v02 \
    libloc_api_wds \
    libloc_base_util \
    libloc_core \
    libloc_mq_client \
    libloc_socket \
    libloc_util \
    liblocaltm_capture.uniplugin@1.0 \
    liblocation_api \
    liblocation_api_msg \
    liblocation_client_api \
    liblocation_integration_api \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_common \
    liblowi_wifihal \
    liblx-ar_util \
    liblx-osal \
    libmaskdetection.uniplugin@1.0 \
    libmcaimegpu.samsung \
    libmctfengine_stub \
    libmdmdetect \
    libmdsprpc \
    libmemutils \
    libmfGhostDetection \
    libmfec \
    libminkdescriptor \
    libminksocket_vendor \
    libmm-hdcpmgr \
    libmmcamera_bestats \
    libmmcamera_cac \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmmcamera_pdpc \
    libmmosal_vendor \
    libmpbase_vendor \
    libmultiobject_tracker \
    libnanopb \
    libndfilter_preview.uniplugin@1.0 \
    libnicm \
    libnicm_dsi \
    libnicm_utils \
    liboemcrypto \
    libopencv \
    libopencv3a \
    libopestriping \
    libops \
    libos \
    libpadm \
    libpal_net_if \
    libpantilt_detector.uniplugin@1.0 \
    libpdmapper \
    libpdnotifier \
    libperipheral_client \
    libpersonalimprinting.uniplugin@1.0 \
    libpet_detector.uniplugin@1.0 \
    libpetcamera_engine \
    libphotohdr_vendor \
    libprofileparamstorage \
    libprotobuf-cpp-full-21.7 \
    libprotobuf-cpp-lite-21.7 \
    libqc2audio_base \
    libqc2audio_basecodec \
    libqc2audio_core \
    libqc2audio_hooks \
    libqc2audio_hwaudiocodec \
    libqc2audio_platform \
    libqc2audio_swaudiocodec \
    libqc2audio_utils \
    libqcbor \
    libqcc_file_agent \
    libqcc_sdk \
    libqcci_legacy \
    libqcmaputils \
    libqcodec2_base \
    libqcodec2_basecodec \
    libqcodec2_core \
    libqcodec2_cvpfilter \
    libqcodec2_filterbase \
    libqcodec2_hooks \
    libqcodec2_imgtxrfilter \
    libqcodec2_mockfilter \
    libqcodec2_platform \
    libqcodec2_utils \
    libqcodec2_v4l2codec \
    libqdcm-algo \
    libqdcm-json-mode-parser \
    libqdcm-mode-parser \
    libqdi \
    libqdp \
    libqdpr \
    libqfp_sensortest \
    libqisl \
    libqll \
    libqll10 \
    libqllengine \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_csvt_srvc \
    libqmi_encdec \
    libqmi_legacy \
    libqmiservices \
    libqrtr \
    libqrtrclient \
    libqseed3 \
    libqsegnet \
    libqsh \
    libqshcamera \
    libqsocket \
    libqspm-mem-utils-vendor \
    libqtigefar \
    librapidscorerplus \
    librcmask \
    librechdr10plus.sec \
    librechdr10plus \
    librecordalive \
    libril_sem \
    librmengine_plus.uniplugin@1.0 \
    librpmb \
    libsamsungcamerahal \
    libsamsungcamerahalutils \
    libsamsungcamerahwl_impl \
    libsavscmn \
    libsavsvc \
    libscaler_hw.unifunc \
    libscaler_sw.unifunc \
    libscenedetector.uniplugin@1.0 \
    libscveCommon \
    libscveCommon_stub \
    libscveObjectSegmentation \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libsdm-color \
    libsdm-colormgr-algo \
    libsdm-disp-vndapis \
    libsdmextension \
    libsdsprpc \
    libsdynatm \
    libsec-ril \
    libsec2imageformatfilter \
    libsec_esek \
    libsec_semHalTlc \
    libsec_semRil_vendor \
    libsecaudiocoreutils \
    libsecaudioinfo \
    libsecaudiolevel \
    libsecfr_engine \
    libsecfr_model \
    libsecnativefeature \
    libsecril-client_vendor \
    libsecsettingsmanager \
    libsecsuperresolution_wrapper_v1.camera.samsung \
    libsegmentationeffect.uniplugin@1.0 \
    libsegmentationeffect_capture.uniplugin@1.0 \
    libsehbluetooth_audio_session_aidl \
    libsemnativecarrierfeature \
    libsensorlistener \
    libsensorndkbridge \
    libsensorslog \
    libsfeShiftExtrapolation \
    libsfp_sensor \
    libsfp_teegw \
    libshctrl \
    libshotsuggestion \
    libshotsuggestion_engines \
    libshsc \
    libsi \
    libsimba.media.samsung \
    libsingle_portrait_preview.uniplugin@1.0 \
    libskeymint10device \
    libskeymint_cli \
    libsmartfocus.uniplugin@1.0 \
    libsmemlog \
    libsnap_compute \
    libsnap_compute_wrapper \
    libsnap_qnn \
    libsnap_vndk \
    libsnapdragoncolor-manager \
    libsnapdragoncolor-qdcm \
    libsnaplite_native \
    libsnaplite_wrapper \
    libsnpe_dsp_domains_v3 \
    libsnpe_wrapper \
    libsns_api \
    libsns_device_mode_stub \
    libsns_direct_channel_stub \
    libsns_dynamic_loader_stub \
    libsns_registry_skel \
    libsns_remote_proc_state_stub \
    libsnsapi \
    libsnsdiaglog \
    libsnsutils \
    libsoc_helper \
    libsocial_image_enhancement.uniplugin@1.0 \
    libspatializerparamstorage \
    libspcom \
    libspeakercalibration \
    libspictrl_vendor \
    libspl \
    libspukeymintdeviceutils \
    libsrib_CNNInterface.camera.samsung \
    libsrib_humanaware_engine.camera.samsung \
    libssc_default_listener \
    libssd \
    libssengine.uniplugin@1.0 \
    libstagefright_foundation_vendor \
    libstreamparser \
    libswregistrationalgo \
    libsynaFpSensorTestNwd \
    libsynergy_loc_api \
    libsynx \
    libsys_info_cache \
    libsysmon_cdsp_skel \
    libsystem_health_mon \
    libtensorflowLite.singletake.camera.samsung \
    libtensorflowlite.camera.samsung \
    libtensorflowlite_c \
    libtensorflowlite_gpu.camera.samsung \
    libtestutils \
    libtfestriping \
    libtflitecore \
    libthermalclient \
    libthreadutils \
    libtime_genoff \
    libtinyxml2_1 \
    libtrustedapploader \
    libtswrappercommon \
    libubifocus \
    libunidatamanager \
    libuniplugin \
    libvdis_core \
    libvibratorutils \
    libvicom \
    libvideobeauty.arcsoft \
    libvideobeauty.uniplugin@1.0 \
    libvideobeauty_capture.uniplugin@1.0 \
    libvideobeauty_interface \
    libvideoml \
    libvideotxr \
    libvideoutils \
    libvkmanager_vendor \
    libvmfilexfer \
    libvmmem \
    libvui_intf \
    libwifiobserver \
    libxml \
    libxtadapter \
    libzoomroi.samsung \
    libzoomroi_lite.samsung \
    libdrmclearkeyplugin \
    nfc_nci_nxpsn \
    qti.video.utils.videobufferlayout \
    service-listener-ext-aidl-V1-ndk_vendor \
    libQnnHtp \
    libQnnHtpV75Stub \
    libQnnSystem \
    libasphere \
    libaudioeffectoffload \
    libaudiosaplus_sec \
    libmyspace \
    libquasar \
    libsamsungSoundbooster_plus \
    libshoebox \
    libswdap \
    libswspatializer \
    unihal_android \
    unihal_cutils \
    unihal_entry \
    unihal_filter_unit \
    unihal_main \
    unihal_scenario \
    unihal_uniplugin@1.0 \
    vendor.display.postproc@1.0 \
    vendor.qti.data.mwqem@1.0 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.diaghal@1.0_vendor \
    vendor.qti.esepowermanager@1.0 \
    vendor.qti.gnss-V5-ndk \
    vendor.qti.gnss-service \
    vendor.qti.hardware.AGMIPC@1.0-impl \
    vendor.qti.hardware.ListenSoundModel@1.0-impl \
    vendor.qti.hardware.ListenSoundModel@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.bttpi-V3-ndk \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.camera.aon-service-impl \
    vendor.qti.hardware.camera.offlinecamera-service-impl \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.dynamicdds@1.1 \
    vendor.qti.hardware.data.flow@1.0 \
    vendor.qti.hardware.data.flow@1.1 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.lce@1.0 \
    vendor.qti.hardware.dsp@1.0 \
    vendor.qti.hardware.fm@1.0_vendor \
    vendor.qti.hardware.mwqemadapter@1.0 \
    vendor.qti.hardware.pal@1.0-impl \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.qccsyshal@1.1 \
    vendor.qti.hardware.qccsyshal@1.2 \
    vendor.qti.hardware.qdutils_disp@1.0 \
    vendor.qti.hardware.qseecom-V1-ndk_vendor \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.radio.atfwd-V1-ndk \
    vendor.qti.hardware.slmadapter@1.0 \
    vendor.qti.hardware.trustedui@1.0 \
    vendor.qti.hardware.trustedui@1.1 \
    vendor.qti.hardware.trustedui@1.2 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.latency@2.0 \
    vendor.qti.latency@2.1 \
    vendor.qti.latency@2.2 \
    vendor.qti.qccvndhal_aidl-V1-ndk_vendor \
    vendor.qti.qccvndhal_aidl-halimpl \
    vendor.qti.qspmhal-V1-ndk \
    vendor.samsung.hardware.audio@1.0 \
    vendor.samsung.hardware.biometrics.face-V3-ndk \
    vendor.samsung.hardware.biometrics.fingerprint-V1-ndk \
    vendor.samsung.hardware.bluetooth.audio-V2-ndk_vendor \
    vendor.samsung.hardware.bluetooth.audio-impl \
    vendor.samsung.hardware.bluetooth@2.0 \
    vendor.samsung.hardware.camera.device-V1-ndk \
    vendor.samsung.hardware.camera.provider-V1-ndk \
    vendor.samsung.hardware.gnss-V2-ndk_platform \
    vendor.samsung.hardware.hyper-V2-ndk \
    vendor.samsung.hardware.keymint-V3-ndk \
    vendor.samsung.hardware.nfc_aidl-V1-ndk \
    vendor.samsung.hardware.radio-V1-ndk \
    vendor.samsung.hardware.radio.bridge-V1-ndk \
    vendor.samsung.hardware.radio.channel-V1-ndk \
    vendor.samsung.hardware.radio.data-V1-ndk \
    vendor.samsung.hardware.radio.messaging-V1-ndk \
    vendor.samsung.hardware.radio.sim-V1-ndk \
    vendor.samsung.hardware.security.drk-V1-ndk \
    vendor.samsung.hardware.security.drk@2.0 \
    vendor.samsung.hardware.security.hermes-V1-ndk \
    vendor.samsung.hardware.thermal-V1-ndk \
    vendor.samsung.hardware.thermal@1.0 \
    vendor.samsung.hardware.vibrator-V5-ndk \
    libdsp_streamer_binning \
    libhme_dsp_skel \
    libdiag_system \
    vendor.qti.diaghal@1.0 \
    vendor.qti.hardware.qseecom-V1-ndk \
    vendor.qti.imsrtpservice@3.0 \
    vendor.qti.imsrtpservice@3.1 \
    vendor.qti.qccvndhal_aidl-V1-ndk \
    TimeService \
    HotwordEnrollmentOKGoogleEx4HEXAGON \
    HotwordEnrollmentXGoogleEx4HEXAGON \
    uimservicelibrary \
    com.android.hotwordenrollment.common.util \
    vendor.qti.ims.connection-V1.0-java \
    vendor.qti.ims.factory-V2.0-java \
    vendor.qti.ims.factory-V2.1-java \
    vendor.qti.ims.factory-V2.2-java \
    vendor.qti.ims.rcssip-V1.0-java \
    vendor.qti.ims.rcssip-V1.1-java \
    vendor.qti.ims.rcssip-V1.2-java \
    vendor.qti.ims.rcsuce-V1.0-java \
    vendor.qti.ims.rcsuce-V1.1-java \
    vendor.qti.ims.rcsuce-V1.2-java \
    android.hardware.gnss-aidl-service-qti.xml \
    android.hardware.security.keymint-service.xml \
    bluetooth_audio.xml \
    bttpi-saidl.xml \
    iweaver_aidl_v2_manifest.xml \
    nfc-service-nxp.xml \
    qms-saidl.xml \
    sec_c2_manifest_default0_1_2.xml \
    secure_element-service-nxp.xml \
    vendor.qti.camera.aon-impl.xml \
    vendor.qti.camera.offlinecamera-impl.xml \
    vendor.qti.camera.postproc-impl.xml \
    vendor.qti.diag.hal.service.xml \
    vendor.qti.gnss-service.xml \
    vendor.samsung.hardware.camera.provider-service.xml \
    vendor.samsung.hardware.thermal-default.xml \
    vendor.samsung.hardware.vibrator-default.xml \
    ATFWD-daemon \
    adpl \
    adsprpcd \
    cdsprpcd \
    cnss-daemon \
    diag-router \
    dspservice \
    hermesd \
    android.hardware.bluetooth@1.1-service-qti \
    android.hardware.gnss-aidl-service-qti \
    android.hardware.nfc-service.nxp \
    android.hardware.secure_element-service.nxp \
    android.hardware.security.keymint-service.samsung \
    rild \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.trustedui@1.0-service-qti \
    vendor.qti.media.c2@1.0-service \
    vendor.samsung.hardware.camera.provider-service_64 \
    vendor.samsung.hardware.thermal-service \
    vendor.samsung.hardware.vibrator-service \
    init.kernel.post_boot-pineapple \
    init.kernel.post_boot \
    init.qcom.class_core \
    init.qcom.post_boot \
    init.qcom.sensors \
    init.qti.kernel \
    init.qti.media \
    init.qti.qcv \
    init.qti.write \
    ipacm-diag \
    irsc_util \
    ks \
    loadalgo \
    loc_launcher \
    lowi-server \
    pd-mapper \
    pktlogconf \
    pm-proxy \
    pm-service \
    ppd \
    qcc-vendor \
    qdcmss \
    qms \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    qwesd \
    rmt_storage \
    sec_nvm \
    sensors.qti \
    shsusrd \
    spdaemon \
    sscrpcd \
    ssgtzd \
    ssr_diag \
    ssr_setup \
    subsystem_ramdump \
    system_dlkm_modprobe \
    tftp_server \
    thermal-engine-v2 \
    time_daemon \
    trusteduilistener \
    vendor_modprobe \
    xtra-daemon

PRODUCT_PACKAGES += \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so
